# application.yml
server:
  port: 8080

spring:
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    excluded-view-names:
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/SubtitleTranslationTool?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.niit.subtitletranslationtool.entity

file:
  # 相对路径，将在项目根目录下创建uploads文件夹
  upload-dir: uploads/
  # 也可以设置为绝对路径，例如 C:/subtitle_uploads

temp:
  audio-dir: temp/audio/