# application.yml（修正缩进后的完整正确配置）
server:
  port: 8080

spring:
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    excluded-view-names:
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/SubtitleTranslationTool?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  # 关键修正：mvc 和 web 是 spring 的直接子节点（原错误嵌套在 temp 节点下）
  mvc:
    static-path-pattern: /static/**  # 静态资源访问前缀：所有/static/开头的请求指向静态资源目录
  web:
    resources:
      static-locations:
        - classpath:/static/          # 默认类路径静态资源（保留）
        - classpath:/public/          # 默认类路径静态资源（保留）
        - file:${user.dir}/outputs/   # 新增：将项目根目录下的outputs目录映射为静态资源

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.niit.subtitletranslationtool.entity

file:
  upload-dir: uploads/
  translated-srt-dir: "temp/srt_translated/"
  subtitled-video-dir: "outputs/video_subtitled/"  # 新增压制视频存储目录

temp:
  audio-dir: temp/audio/  # 注意：temp 节点下仅保留 audio-dir 配置（原错误嵌套了 mvc/web）

whisper:
  executable-path: "D:/code/Subtitle_translation_tool/Pyhton/faster-whisper-xxl.exe"
  model: "large-v3-turbo"                                # 使用大模型保证精度
  device: "cuda"                                         # 优先使用GPU加速
  output-dir: "temp/srt_original/"                       # 原始SRT存储目录
  vad-filter: true                                       # 启用语音活动检测
  timeout-multiplier: 3                                  # 超时倍数（音频时长×2）

# Doubao API配置
doubao:
  api-base: "https://ark.cn-beijing.volces.com/api/v3"
  api-key: "34cc6e77-8723-4668-8a2a-1b41d1ac1329"  # 建议实际部署时改为环境变量注入
  model: "doubao-1-5-pro-32k-250115"
  max-context-length: 32000  # 模型最大上下文长度
  timeout: 60000  # API调用超时时间（毫秒）